Cloud Run deploy workflow GCP deploy refinements

diff --git a/.github/workflows/publish-dev-image.yml b/.github/workflows/publish-dev-image.yml
--- a/.github/workflows/publish-dev-image.yml
+++ b/.github/workflows/publish-dev-image.yml
@@ -39,7 +39,7 @@ on:
         required: false
 
 jobs:
-  publish-wrapped-artifact:
+  publish-dev-image:
     runs-on: ubuntu-latest
     env:
       GCP_REG_TOKEN: ${{ secrets.gcp_registry_token }}
@@ -84,9 +84,9 @@ jobs:
       - name: List files from artifact
         run: ls -laR ./.artifact
 
-      - name: "Fail if not latest build or no tag is provided"
-        if: ${{ inputs.push-image && github.ref_type != 'tag'  && ! inputs.output-image-tag-latest }}
-        run: exit 42
+      # - name: "Fail if no latest build or no tag is provided"
+      #   if: ${{ inputs.push-image && github.ref_type != 'tag'  && ! inputs.output-image-tag-latest }}
+      #   run: exit 42
 
       - name: "Adding \"latest\" tag"
         if: ${{ inputs.output-image-tag-latest }}
@@ -99,9 +99,10 @@ jobs:
           echo "TAG ADDED: ${{ github.ref_name }}"
 
       - name: "Adding image tag for GCP"
-        if: ${{ github.ref_type == 'tag' && env.GCP_REG_TOKEN }}
+        if: ${{ env.GCP_REG_TOKEN }}
+        # if: ${{ github.ref_type == 'tag' && env.GCP_REG_TOKEN }}
         run: |
-          echo "IMAGE_TAG_GCP=${{ inputs.gcp_registry_domain }}/${{ inputs.gcp_registry_image }}:${{ github.ref_name }}" >> $GITHUB_ENV
+          # echo "IMAGE_TAG_GCP=${{ inputs.gcp_registry_domain }}/${{ inputs.gcp_registry_image }}:${{ github.ref_name }}" >> $GITHUB_ENV
           echo "IMAGE_TAG_GCP_LATEST=${{ inputs.gcp_registry_domain }}/${{ inputs.gcp_registry_image }}:latest" >> $GITHUB_ENV
           echo "TAG ADDED: ${{ github.ref_name }}"
 
@@ -112,8 +113,11 @@ jobs:
           context: .
           file: ${{ inputs.dockerfile }}
           tags: |
-            ${{ env.IMAGE_TAG }}
-            ${{ env.IMAGE_TAG_LATEST }}
             ${{ env.IMAGE_TAG_GCP }}
             ${{ env.IMAGE_TAG_GCP_LATEST }}
+          # tags: |
+          #   ${{ env.IMAGE_TAG }}
+          #   ${{ env.IMAGE_TAG_LATEST }}
+          #   ${{ env.IMAGE_TAG_GCP }}
+          #   ${{ env.IMAGE_TAG_GCP_LATEST }}
             
